# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 971cda56d09cb3b4d55c65155e89f0723e6923b36e7fd7c1844b2d08a887e7fd76074bb567f26c21ede3b39a5c4d94f900f63ac86c38ae6657e8bacc5dae52b6

test:
  secret_key_base: ae67665731b76dff3743d5288970acec411ffb948c6498a15dcc4775d0b395b092959887f4084641be407a5cdeba8c8935fc15f8ac94b10fe3e867f748df8342

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
